name: Deploy Azure SQL Database

on:
  push:
    branches:
      - main
    paths:
      - 'sql/**'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Install sqlcmd
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
          echo "/opt/mssql-tools18/bin" >> $GITHUB_PATH

      - name: Deploy SQL Scripts
        run: |
          for file in $(find sql -name "*.sql" | sort)
          do
            echo "Executing $file"

            sqlcmd \
              -S ${{ secrets.SQL_SERVER_NAME }}.database.windows.net \
              -d ${{ secrets.SQL_DATABASE_NAME }} \
              -U ${{ secrets.SQL_USERNAME }} \
              -P "${{ secrets.SQL_PASSWORD }}" \
              -N \
              -C \
              -b \
              -i "$file"
          done
